<?php
namespace GDO\Core\Method;

use GDO\Core\GDO_ArgError;
use GDO\Core\GDT;
use GDO\Core\GDT_Enum;
use GDO\UI\GDT_HTML;
use GDO\UI\MethodPage;

final class Day0 extends MethodPage
{

    public function gdoParameters(): array
    {
        return [
            GDT_Enum::make('iam')->enumValues('sure', 'not_sure')->initial('not_sure')->notNull(),#->positional(),
        ];
    }


    /**
     * @throws GDO_ArgError
     */
    public function execute(): GDT
    {
        if ($this->isSure())
        {
            return GDT_HTML::make()->var(parent::execute()->render());
        }
        return parent::execute(); // TODO: Change the autogenerated stub
    }

    /**
     * @throws GDO_ArgError
     */
    private function isSure(): bool
    {
        return $this->gdoParameterValue('iam') === 'sure';
    }

}
